CREATE DATABASE IF NOT EXISTS employeefeedback;

use employeefeedback;

create table ORGANIZATIONS
( ORGANIZATION_ID INT AUTO_INCREMENT PRIMARY KEY,
  ORGANIZATION_NAME VARCHAR(100) NOT NULL,
  ORGANIZATION_DESC VARCHAR(500),
  STATUS ENUM ('A','I') DEFAULT 'A',
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

create table ADDRESS_DETAIL
( ADDRESS_ID INT AUTO_INCREMENT PRIMARY KEY,
  FULL_ADDRESS VARCHAR(200) NOT NULL,
  PINCODE VARCHAR(50) NOT NULL,
  STATUS ENUM ('A','I') DEFAULT 'A',
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

create table EMPLOYEE
( EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
  EMPLOYEE_NAME VARCHAR(100) NOT NULL,
  DESIGNATION VARCHAR(50) NOT NULL,
  ORGANIZATION_ID INT NOT NULL,
  ADDRESS_ID INT NOT NULL,
  STATUS ENUM ('A','I') DEFAULT 'A',
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATIONS(ORGANIZATION_ID),
  FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS_DETAIL(ADDRESS_ID)
);

create table EMPLOYEE_FEEDBACK
( FEEDBACK_ID INT AUTO_INCREMENT PRIMARY KEY,
  EMPLOYEE_ID INT NOT NULL, 
  FEEDBACK_RATING ENUM('1', '2', '3', '4', '5') NOT NULL DEFAULT '1',
  FEEDBACK_COMMENTS VARCHAR(1000),
  STATUS ENUM ('A','I') DEFAULT 'A',
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);
